add deploy

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -7,13 +7,12 @@ on:
       - '*'
 env:
   IMAGE_NAME: andruwkakz/app_for_diplom
-  NAMESPACE: nginx-diplom
-  DEPLOYMENT_NAME: nginx-diplom
+  NAMESPACE: diplom
+  DEPLOYMENT_NAME: diplom
 
 jobs:
   build-docker-image:
-    # runs-on: self-hosted
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     steps:
       # Шаг 1: Клонируем проект
       - name: Checkout Code
@@ -41,3 +40,42 @@ jobs:
       # Шаг 5: Пушим Docker образ в Docker Hub
       - name: Push Docker Image
         run: docker push  ${{ env.IMAGE_NAME }}:${{ env.TAG }}
+
+  deploy_app:
+    needs: build
+    runs-on: self-hosted
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: List files in the working directory
+        run: |
+          ls -la
+
+      - name: Extract version from tag or commit message
+        run: |
+          echo "GITHUB_REF: ${GITHUB_REF}"
+          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
+            VERSION=${GITHUB_REF#refs/tags/}
+          else
+            VERSION=$(git log -1 --pretty=format:%B | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+' || echo "")
+          fi
+          if [[ -z "$VERSION" ]]; then
+            echo "No version found in the commit message or tag"
+            exit 1
+          fi
+          VERSION=${VERSION//[[:space:]]/}  # Remove any spaces
+          echo "Using version: $VERSION"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+
+      - name: Replace image tag in app.yaml
+        run: |
+          if [ ! -f /home/app_for_diplom/manifest/app.yaml ]; then
+            echo "app.yaml not found in the current directory"
+            exit 1
+          fi
+          sed -i "s|image: {{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${{ env.VERSION }}|" /home/app_for_diplom/manifest/app.yaml 
+
+      - name: Apply Kubernetes manifests
+        run: |
+          kubectl apply -f /home/app_for_diplom/manifest/app.yaml -n diplom
